# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PHY 432
tagline: Computational Methods in Physics
description: A class at Arizona State University for learning how to use Python (and some software engineering) to solve problems in physics. 
author: Arunima Singh
baseurl: '/PHY432' # the subpath of your site, e.g. /blog
url: 'https://pyforphy.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Theme settings
# On GitHub: use remote_theme
remote_theme: just-the-docs/just-the-docs

# local development: use installed theme
# see https://github.com/pmarsceill/just-the-docs/issues/297
# https://github.com/self-xdsd/self-docs for using alternative _config:
# 'bundle exec jekyll serve --config _config_local.yml'
#theme: "just-the-docs"

# logo: "/assets/images/phy432_logo.png"
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Canvas (Spring 2026):
    - 'https://asu.instructure.com/courses/238717'
  Discord:
    - 'https://discord.com/channels/1327758612155859077'
  PyforPhy:
    - 'https://github.com/PyforPhy'
  ASU Physics:
    - 'https://physics.asu.edu'
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

plugins_dir:
  - jekyll-seo-tag

# Custom variables
# ----------------

# About/contact
author:
  name:              'Arunima Singh'
  url:               https://search.asu.edu/profile/3323915
  email:             arunimasingh@asu.edu

# use as {{site.baseurl}}/{{site.data}}
data:                "assets/data"
code:                "assets/code"
figs:                "assets/figs"
images:              "assets/images"
movies:              "assets/movies"
docs:                "assets/docs"
siteresources:       "assets/resources"

course:
 url:                "https://becksteinlab.physics.asu.edu/learning/146/phy432-computational-physics"

canvas:
 name:               "Canvas (ASU PHY432 Spring 2025)"
 url:                https://asu.instructure.com/courses/238717

resources:
 name:               PyforPhy/PHY432-resources
 shortname:          PHY432-resources
 url:                https://github.com/PyforPhy/PHY432-resources
 fileurl:            https://github.com/PyforPhy/PHY432-resources/blob/main
 giturl:             https://github.com/PyforPhy/PHY432-resources.git
 rawurl:             https://github.com/PyforPhy/PHY432-resources/raw/main

org:
 name:               PyforPhy
 shortname:          GitHub site
 url:                https://github.com/PyforPhy

wiki:
 name:               ASU Comp Phys PHY432 Wiki
 shortname:          Wiki
 url:                https://github.com/PyforPhy/PHY432-resources/wiki

nbviewer:
   show:             https://nbviewer.jupyter.org/github
   resources:        https://nbviewer.jupyter.org/github/PyforPhy/PHY432-resources/blob/main
   slides:           https://nbviewer.jupyter.org/format/slides/github/PyforPhy/PHY432-resources/blob/main
